[RD-42114] Fix using the multiline plugin.
scivisum/logstash-input-cloudwatch-logs pull request #2
Opened 2021-07-19 13:46 UTC by tonyhignett

- When you pass a message to it with `@codec.decode` you don't get that message back until you pass another one, because only then does the plugin know that the message has no more lines. So we always call `process_event` with the message from one vent and the metadata from the next one. (More complicated things may also happen with genuinely multiline events.)
- As a result, the last event of each stream is processed in the context of an event from another stream, so appears to be missing. (More complicated things probably go wrong as well.)
- So we have to correlate the messages emitted by the plugin with the original events. To do this, stop using the identity map plugin and group the events by log stream ourselves. Then we can pass them through the multiline plugin stream-by-stream and keep the multiline events lined up with the original ones.

2021-07-22 11:09 UTC, apurtak requested changes

2021-07-22 11:09 UTC, apurtak commented on lib/logstash/inputs/cloudwatch_logs.rb
> +        if events_by_log_stream[cloudwatch_event.log_stream_name].nil?
You can avoid this initialisation by creating the hash like that: `events_by_log_stream = Hash.new { |hash, key| hash[key] = [] }`. The way this works is that it will call the block you pass to `new` for each missing key.

2021-07-22 11:09 UTC, apurtak commented on lib/logstash/inputs/cloudwatch_logs.rb
> +          event_index += logstash_event.get("message").lines.count
This doesn't work if cloudwatch event itself is multi-line, e.g. RDS logs. I added additional log stream to the test group, with this kind of messages.

Perhaps we approach this problem from a wrong direction. Apparently it's possible to configure the `awlogs` driver to handle multi-line messages using patterns. If we can get this to work, we can ditch the multiline codec and our changes to this plugin altogether. See https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_awslogs.html and 
https://docs.docker.com/config/containers/logging/awslogs/

I looked whether we considered this option before, but I didn't see any mentions. We added the multiline codec in [RD-34614].

Docs say there will be a performance hit when using patterns, but we would have to try to see how bad it can get. Luckily, it looks like may be able to test this locally.

2021-07-22 12:23 UTC, tonyhignett commented on lib/logstash/inputs/cloudwatch_logs.rb
> +          event_index += logstash_event.get("message").lines.count
The main downside of this I can see would be that we wouldn't be able to use it to get multiline logs from Lambdas. (People complain that there is no solution for multiline Lambda logging.) But we rarely read logs from lambdas, and we currently don't apply the multiline config to them anyway.

So it does look like a better solution.

2021-07-26 09:34 UTC, apurtak commented
We're going to configure the `awslogs` driver instead of this fix.

2021-07-26 09:34 UTC, closed without merging